"""empty message

Revision ID: 3d6dee62c59a
Revises: d7847a462882
Create Date: 2024-02-08 21:24:34.817751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6dee62c59a'
down_revision = 'd7847a462882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('planets_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('characters_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('characters_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planets_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
